### ISSUE TITLE
Adjust installation task for Litium 8

### ISSUE THREAD

**Issue by martenw** [LitiumAB/Education#21]
## TODO:

- [x] Add instructions on how to add license
- [x] Add dns settings for the application container
- [x] Remove preparation step 6 that is already covered in the docker-task: _Install Docker Desktop to run containers for Litium Apps_
