### ISSUE TITLE
Adjust education slideshow for Litium 8

### ISSUE THREAD

**Issue by martenw** [LitiumAB/Education#57]
- Switch to new logo
   - [x] Change favicon
   - [x] Slide 1 logo
   - [x] Logo on all section-pages
- Adjust slides
   - [x] 5. Goals: adjust certification info to instead inform that exam is scheduled after education
   - [x] 8. Litium is based on standard technology
   - [x] 9. Roadmap
   - [x] 24. Installation pre req
   - [x] Web.config updates - Rewrite to be on common adjustments in appsettings
   - [x] Login to backoffice - Adjust to include info on db-tool
   - [x] Administration UI - Signalr relevant? / remove webforms info / Add info on available extension points
   - [x] Add a slide on Accelerator project structure, 
     - The new `Litium.Accelerator.Administration.Extensions`-project 
     - Info at https://docs.litium.com/documentation/litium-accelerators/develop/accelerator-architecture/accelerator-mvc
   - [x] 41: Field framework - explain Installation/Area
   - [x] 54: Blocks - **Have** data modelling
   - [x] 63. Country & tax class - says same as 50, cleanup
   - [x] 59. Architecture and apis - replace
   - [x] 66-67 componentmodel & service model - better info
   - [x] Moved to separate task #68
   - [x] Moved to separate task #69
   - [x] 111. Event log - remove db
   - [x] 118+. Connect
   - [x] Litium Search - Remove Lucene and add new screenshots
   - [x] Litium Search - Update link on how to create custom index when article is published https://litiumdev-slides.svc.litiumlab.se/#147
      - The page is [available for L7](https://docs.litium.com/documentation/previous-versions/litium-7/architecture/search/elasticsearch/how-to-add-a-search-index) but missing for [L8] (https://docs.litium.com/documentation/architecture/litiumsearch/setup-and-configure-elasticsearch)
   - [x] Review/update all frontend development slides
     - [x] Remove slides on rendering the buy button
     - [x] Add Email slide https://docs.litium.com/documentation/litium-accelerators/develop/front-end-accelerator/accelerator-email
   - [x] License: Since 8.1 throttling is used to limit the dev license
   - [x] 150 Upgrading
   - [x] Remove slide 26. Nuget package for installation
   - [x] 31. Useful tools - remove slide and move info on localtest.me to the tasks
   - [x] [Security token slides](https://litiumdev-slides-7.svc.litiumlab.se/#82) are removed, replace with relevant new slides
   - [x] Add a slide on Litium apps
      -  Get details from meeting notes
   - [x] #97
   - [x] #115
   - [x] #116
   - [x] 3. Agenda: Adjust to reflect changes in slideshow
   - [x] Search for and remove any remaining TODOs

**Comment by martenw** [comment]
Closing, the final items that are not yet completed are converted into separate issues #115 and #166
